functionsDirectory = "/Users/zlatashvets/Documents/Adaptive media/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/zlatashvets/Documents/Adaptive media/web/nextbound-dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build:nextbound"
functions = "/Users/zlatashvets/Documents/Adaptive media/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/"
to = "/nextbound.html?scenario=procedural-loop"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/run"
to = "/.netlify/functions/run"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]